#! /usr/bin/python
# filename: 29.py

'''
How many distinct terms are in the sequence generated by a^b for 
2<=a<=100 and 2<=b<=100
another good way is to use set, only one line
print len(set([i**j for i in xrange(2, 101) for j in xrange(2, 101)]))
'''


def main():
  res = []
  temp = 0
  for a in xrange(2, 101):
    for b in xrange(2, 101):
      temp = a**b
      if temp not in res: res.append(temp)
  print len(res)

if __name__ == '__main__':
  main()
